name = EMS One col
description = one col layout


; ========================================
; Regions
; ========================================
regions[logo] = Logo
regions[menu] = Menu
regions[slogan] = Slogan
regions[content] = Content
regions[list_of_events] = List of events
regions[footer] = Footer


stylesheets[all][] = css/layouts/one_col/one_col.layout.scss
stylesheets[all][] = css/layouts/one_col/one_col.layout.no-query.scss